### ISSUE TITLE
Add a column for technologies being used for the gardens

### ISSUE THREAD

**Issue by dit7ya** [KasperZutterman/Second-Brain#7]
It would be nice to quickly find gardens using the tech stack you are using. Just adding a third column with linked techs used (for example org-roam + hugo) will be hugely useful.

**Comment by KasperZutterman** [comment]
@dit7ya for this, you might want to have a look at https://github.com/MaggieAppleton/digital-gardeners#digital-garden-directory if you want this overview right away.

If you would like to contribute, you could open a pull request where the linked tech is mentioned.
